/*
 * Car pooling API
 *
 * Cabify Car pooling challenge
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class HealthApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Indicate the service has started up correctly and is ready to accept requests.</remarks>
        /// <response code="200">OK. When the service is ready to receive requests.</response>
        [HttpGet]
        [Route("/status")]
        [ValidateModelState]
        [SwaggerOperation("StatusGet")]
        public virtual IActionResult StatusGet()
        { 
            return StatusCode(200);
        }
    }
}
